### ISSUE TITLE
Passing height and width to intialize() and update()

### ISSUE THREAD

**Issue by ianwcarlson** [skellyb/react-d3-wrap#13]
Seems like it would be useful to have height and width available to the calculate vertices and such.  What do you think?  I'd be happy to do a PR.

**Comment by skellyb** [comment]
I'm open to a PR, maybe a dimensions object as a fourth parameter — `{width, height}`.

Also, without changing anything, you could access those values via props.

**Comment by ianwcarlson** [comment]
I haven't responded because my thoughts have changed pretty significantly on this.  We ended up setting the Viewbox attributes as it made scaling way easier.  We also removed the destroy and just auto removed all the D3 children on the parent selection.  Anyway, I can show you what I've come up with, but it's pretty different so I'm not sure if you want a PR.

**Comment by skellyb** [comment]
I'm always happy to see how this is being used in practice. Share what you've come up with!
