### ISSUE TITLE
initialize() method?

### ISSUE THREAD

**Issue by mindjuice** [skellyb/react-d3-wrap#2]
Hey...I was just about to genericize the React D3 wrapper I've been using when I thought "Surely someone has done this already!"  And here we go!

One thing I have been doing in my wrapper is separating the initialization from the update, so things that only need to be done once don't get called again on an update.

I call `initialize()` and then `update()` in my `componentDidMount()`, and just `update()` in `shouldComponentUpdate()` (instead of in `componentDidUpdate()`, which makes the update slightly faster).

How are you currently handling initialization vs. updates?

**Comment by skellyb** [comment]
I surprised someone else hadn't set this up.
1. Adding an `initialize` method makes sense to me. My current use case is really simple, so I've been doing everything in `update`, but it'd be nice to have the option.
2. I prefer `componentDidUpdate` for `update` calls because I want to know state and props updates are good to go.

Thanks for the feedback. I'll add `initialize` call today.

**Comment by mindjuice** [comment]
I spent some time looking at how other D3 code handles this and one way to separate the initialization step from the update is to have a main container component.  Then you try to select it and use an `enter()` call to run code that should only run once.  From that point on it will exist.

```
// Trick to just append the svg skeleton once (from "Developing a D3.js Edge")
var svg = d3.select(this)
    .selectAll("svg")
    .data([_data]);  // There is one data element and it will be bound to the svg
svg.enter().append("svg")
    .classed("chart", true);
```

You could also use `.call(initialize())` after the `append()` instead, and if you already have an `<svg>` tag in your outer React component, you could add an inner container like `<g>` here.

I'm also thinking though that I don't really want to overly mix my React code and my D3 code, and I'd prefer to not create a new React subclass for each chart I want to make.  I'm considering having a generic wrapper component that can host any D3 chart.  Something like this:

```
let MyD3LineChart = import './line-chart';  // This is just pure D3 code with no React stuff

// Set some options, etc. just as you would in normal D3 code
let lineChartInstance = LineChart().setSomeOption(true);

// Render the chart through the wrapper
<ReactD3 chart={lineChartInstance} data={this.props.summaryData} width={w} height={h}/>
```

The wrapper would look something like this:

```
let ReactD3 = React.createClass({

    render: function() {
      let classes = classnames('react-d3', this.props.classes);
      return <svg className={classes} width={ this.props.width } height={ this.props.height } ></svg>;
    },

    // Select the SVG node, bind the data and call the chart
    renderD3: function() {
      d3.select(React.findDOMNode(this))
        .data(this.props.data)
        .call(chart);
    },

    componentDidMount: function () {
      this.renderD3();
    },

    shouldComponentUpdate: function(props) {
      if ((this.props.width !== props.width) || (this.props.height !== props.height)) {
        let svg = React.findDOMNode(this);
        svg.setAttribute("style", "width:" + props.width + "px;height:" + props.height + "px;");
      }
      this.renderD3();

      // Always skip React's render step (it will be run once at initialization though)
      return false;
    }
});
```

Obviously there are some things missing here, like where is the right place to keep the `lineChartInstance`, and when do you recreate it if you want to change options.  So this is still a work in progress / thought experiment.

Curious to hear your thoughts since you've been working in the same area.

**Comment by mindjuice** [comment]
Just FYI, this article also presents an interesting approach: D3 for Math + React for rendering

http://formidablelabs.com/blog/2015/05/21/react-d3-layouts/

You could create components for axes and legends and other common parts of various charts and then build on them.

I'm sort of in an analysis paralysis right now trying to decide which way to go with my current project! :disappointed:

**Comment by skellyb** [comment]
I like the thinking of D3 for math and React for rendering. I've had a lot of the same feelings as the author. I find a lot of D3 difficult to reason about, while React just makes sense to me.

On your comment above, I initially started with a separate D3 chart wrapper that plugs into a generic React wrapper ([similar to this](http://blog.siftscience.com/blog/2015/4/6/d-threeact-how-sift-science-made-d3-react-besties)). In the end, for how I'm using this, I liked the idea of creating single components that could be used throughout a project. I didn't see the benefit in the extra complexity.

Good luck!
