### ISSUE TITLE
Replace lodash.assign() with ES6 spread operator

### ISSUE THREAD

**Issue by mindjuice** [skellyb/react-d3-wrap#3]
Since you are using Babel to compile, you can remove the dependency on `lodash.assign` and replace it with an ES6 spread operator (`...options`) like so:

```
return {
  {
    margin: {
      top: 0,
      bottom: 0,
      left: 0,
      right: 0
    },
    xaxis: { orientation: 'bottom' },
    yaxis: { orientation: 'left' }
  },
  ...options
};
```

I can try to submit a PR on this sometime this week if you agree.

**Comment by skellyb** [comment]
Funny, I just saw this usage of the spread operator somewhere else yesterday. I didn't even know this was possible. Do you have any documentation you could share? Everything I've found is about arrays and function arguments.

To answer your question, I'm all for getting rid of the dependency – PR welcome.

**Comment by mindjuice** [comment]
Check out this link.  Scroll down to "Object Destructuring": https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Destructuring_assignment
