### ISSUE TITLE
Usage example

### ISSUE THREAD

**Issue by nascif** [skellyb/react-d3-wrap#5]
Could you provide a complete (running) example, perhaps in a bl.ock or JS Fiddle, that shows the component usage?
Something like http://lab.oli.me.uk/d3-to-react-again/

In particular I would be curious about how this approach handles transitions and events.

**Comment by skellyb** [comment]
Good question. Let me see what I can come up with. This might not happen until later in the week.

**Comment by nascif** [comment]
Here is a suggestion:
http://vallandingham.me/interactive_networks.html
This interactive visualization has a tightly integrated D3 graph and a few controls. You could use react for the controls, and "wrap" the visualization with your library.
